@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam linetype ortho
hide enum methods


package model #eeaaff{

    class Game {
        - _observers : List<GameObserver>
        - _turnNum : int
        - _gridSize : int
        - _islandMode : boolean
        - _traps : List<TrapTypes>
        - _globalWeaponInventory : List<WeaponTypes>
        - _numberPerShip : Map<ShipTypes, Integer>
        - _players : Player[]
        +<<create>>Game()
        - notifyObserversNoMoreShip(player : Integer)
        - notifyObserversTurnNumber()
        - notifyObserversWeaponFound(player : Integer, weaponType : WeaponTypes)
        + isIslandModeActivated() : Boolean
        + getTurnNum() : Integer
        + getPlayerName(player : Integer) : String
        + getTrapInventorySize() : Integer
        + getTrapInIventory(indexTrap : Integer) : Trap
        + setPlayerName(name : String)
        + setGrid(size : Integer, islandMode : Boolean)
        + addGridObserver(observer : GridObserver)
        + addGameObserver(observer : GameObserver)
        + getGridSize() : Integer
        + otherPlayer(player : Integer) : Integer
        + getMaxShipsPossible() : Integer
        + setNumberPerShip(numberPerShip : Map<ShipTypes,Integer>) : Boolean
        + getNumberPerShip() : Map<ShipTypes,Integer>
        + getNumberMaxOfShip(shipType : ShipTypes) : Integer
        + isAllTheShipsAndTrapsPlaced(player : Integer) : Boolean
        + isAllTheWeaponsPLaced(player : Integer) : Boolean
        + placeTrapOnGrid(player : Integer, trap : Trap) : Boolean
        + placeShipOnGrid(player : Integer, ship : Ship) : Boolean
        + placeWeaponOnIsland(player : Integer, weapon : Weapon, cell : Cell) : Boolean
        + shootOnGrid(player : Integer, cell : Cell) : Boolean
        + getObjectTypeByPosition(player : Integer, posx : Integer, posy : Integer) : PlaceableTypes
        + getWeaponInventorySize(player : Integer) : Integer
        + getWeaponNameInInventory(player : Integer, weaponIndex : Integer) : String
        + setWeapon(player : Integer, weaponIndex : Integer) : Boolean
        + washGrid(player : Integer)
        + isTheGameFinished() : Boolean
        + whoWon() : Integer
        + getPlayer(index : Integer) : Player
        + updateShoot(player : Integer, posx : Integer, posy : Integer, hit : Boolean)
        + updateTrapActivated(player : Integer, posx : Integer, posy : Integer, trapType : TrapTypes)
        + updateSearch(player : Integer, posx : Integer, posy : Integer, objectFound : WeaponTypes)
        + updateShipCellPlaced(player : Integer, posx : Integer, posy : Integer)
        + updateTrapPlaced(player : Integer, posx : Integer, posy : Integer, trapType : TrapTypes)
        + updateWeaponPlacedOnIsland(player : Integer, posx : Integer, posy : Integer, weaponType : WeaponTypes)
        + updateShipCellDrowned(player : Integer, posx : Integer, posy : Integer)
        + updateNoMoreShips(player : Integer)
        - isShipHit(s : Ship) : Boolean
        - isShipDrowned(s : Ship) : Boolean
        + getIntactShipsCount() : Integer
        + getHitShipsCount() : Integer
        + getDrownedShipsCount() : Integer
        + getShotsInWater() : Integer
        + getHitCellsCount() : Integer
        + getRemainingShipCells() : Integer
        + getRemainingIslandCells() : Integer
        + getUsedWeapons() : List<WeaponTypes>
    }

    interface GameObserver <<interface>>{
        + updateNoMoreShips(player : Integer)
        + updateTurnNum(turnNum : Integer)
        + updateWeaponFound(player : Integer, weaponType : WeaponTypes)
    }

    enum Axis <<enum>>{
        VERTICAL
        HORIZONTAL
    }

    class Player {
        - _name : String
        - _grid : Grid
        - _equippedWeapon :  Weapon
        - _weaponInventory : List<Weapon>
        +<<create>>Player(name : String)
        + getName() : String
        + setGrid(grid : Grid)
        + addGridObserver(observer : GridObserver)
        + setMaxShipsCells(maxShipsCells : Integer)
        + getObjectByPosition(cell : Cell) : Placeable
        + getNumberOfShipByType(shipType : ShipTypes) : Integer
        + getNumberOfTrapsByType(trapType : TrapTypes) : Integer
        + getNumberOfWeaponsOnIslandByType(weaponType : WeaponTypes) : Integer
        + placeShip(ship : Ship) : Boolean
        + placeTrap(trap : Trap) : Boolean
        + placeWeaponOnIsland(weapon : Weapon, cell : Cell) : Boolean
        + shoot(otherPlayer : Player, cell : Cell) : Boolean
        + addWeaponInInventory(weapon : Weapon)
        + setEquippedWeapon(weaponIndex : Integer) : Boolean
        + getEquippedWeapon() : Weapon
        + getWeaponInventorySize() : Integer
        + getWeaponInInventory(weaponIndex : Integer) : Weapon
        + washGrid()
        + hasNoMoreShips() : Boolean
        + getIntactShipsCount() : Integer
        + getHitShipsCount() : Integer
        + getDrownedShipsCount() : Integer
        + getShotsInWater() : Integer
        + getHitCellsCount() : Integer
        + getRemainingShipCells() : Integer
        + getRemainingIslandCells() : Integer
        + getUsedWeapons() : List<WeaponTypes>
        + getWeaponInventory() : List<WeaponTypes>
    }

    class Grid {
        - _width : Integer
        - _height : Integer
        - _player : Integer
        - _islandMode : Boolean
        - _maxShipsCells : Integer
        - _placedObjects : List<Placeable>
        - _observers : List<GridObserver>
        +<<create>>Grid(width : Integer, height : Integer, player : Integer)
        +<<create>>Grid(width : Integer, height : Integer,player : Integer, islandMode : Boolean)
        - constructIsland()
        + addObserver(observer : GridObserver)
        + notifyObserversShoot(posx : Integer, posy : Integer, hit : Boolean)
        + notifyObserversTrapActivated(posx : Integer, posy : Integer, trapType : TrapTypes)
        + notifyObserversSearch(posx : Integer, posy : Integer, objectFound : WeaponTypes)
        + notifyObserversShipCellPlaced(posx : Integer, posy : Integer)
        + notifyObserversTrapPlaced(posx : Integer, posy : Integer, trapType : TrapTypes)
        + notifyObserversWeaponPlaced(posx : Integer, posy : Integer, weaponType : WeaponTypes)
        + notifyObserversShipCellDrowned(posx : Integer, posy : Integer)
        + notifyObserversNoMoreShip()
        + setMaxShipsCells(maxShipsCells : Integer)
        + isOccupied(cell : Cell) : Boolean
        + isOccupiedBy(cell : Cell, PlaceableTypes type) : Boolean
        + getObjectByPosition(cell : Cell) : Placeable
        + getNumberOfShipByType(shipType : ShipTypes) : Integer
        + getNumberOfTrapByType(trapType : TrapTypes) : Integer
        + getNumberOfWeaponOnIslandByType(weaponType : WeaponTypes) : Integer
        + isInGrid(cell : Cell) : Boolean
        + canPlaceObject(placeable : Placeable) : Boolean
        + placeObject(placeable : Placeable) : Boolean
        + placeImpact(cell : Cell) : Boolean
        + shoot(cell : Cell, weapon : Weapon) : Boolean
        + isTheShipDrowned(ship : Ship) : Boolean
        + getIslandObject(cell : Cell) : Placeable
        + washGrid()
        + placeWeaponOnIsland(weapon : Weapon, cell : Cell) : Boolean
        + allShipsDead() : Boolean
    }
    interface GridObserver <<interface>> {
        + updateShoot(player : Integer, posx : Integer, posy : Integer, hit : Boolean)
        + updateTrapActivated(player : Integer, pox : Integer, posy : Integer, trapType : TrapTypes)
        + updateSearch(player : Integer, posx : Integer, posy : Integer, objectFound : WeaponTypes)
        + updateShipCellPlaced(player : Integer, posx : Integer, posy : Integer)
        + updateTrapPlaced(player : Integer, posx : Integer, posy : Integer, trapType : TrapTypes)
        + updateWeaponPlacedOnIsland(player : Integer, posx : Integer, posy : Integer, weaponType : WeaponTypes)
        + updateShipCellDrowned(player : Integer, posx : Integer, posy : Integer)
        + updateNoMoreShips(player : Integer)
    }

    enum PlaceableTypes <<enum>>{
        SHIP
        TRAP
        IMPACT
        ISLANDPART
        WEAPON
    }
    interface Placeable <<interface>> {
        + getSize() : Integer
        + getCell(index : Integer) : Cell
        + hasThisPosition(cell : Cell) : Boolean
        + getType() : PlaceableTypes
    }

    class Impact implements Placeable {
        - _position : Cell
        +<<create>>Impact(cell : Cell)
        + getSize() : Integer
        + getCell(index : Integer) : Cell
        + hasThisPosition(cell : Cell) : Boolean
        + getType() : PlaceableTypes
    }

    class IslandPart implements Placeable{
        - _position : Cell
        - _placedObjects : Placeable
        + <<create>>Island(cell : Cell)
        + getSize() : Integer
        + getCell(index : Integer) : Cell
        + hasThisPosition(cell : Cell) : Boolean
        + getType() : PlaceableTypes
        + isThereAnObject() : Boolean
        + getPlacedObject() : Placeable
        + setPlacedObject(placeable : Placeable)
    }

    class Ship implements Placeable {
        - _positions : List<Cell>
        - _shipType : ShipTypes
        + <<create>>Ship(shipType : ShipTypes, cells : List<Cell>)
        + getSize() : Integer
        + getCell(index : Integer) : Cell
        + hasThisPosition(cell : Cell) : Boolean
        + getType() : PlaceableTypes
        + getShipType() : ShipTypes
    }
    enum ShipTypes <<enum>>{
        AircraftCarrier
        Cruiser
        Destroyer
        Submarine
        Torpedo
        + getSize() : Integer
        + toString() : String
    }

    package traps #ff4040 {
    abstract Trap <<abstract>> implements model.Placeable {
        - _position : Cell
        +<<create>>Trap(cell : Cell)
        + getSize() : Integer
        + getCell(index : Integer) : Cell
        + hasThisPosition(cell : Cell) : Boolean
        + getType() : PlaceableTypes
        {abstract} getTrapType() : TrapTypes
        {abstract} execTrap(attackGrid : Grid, receiveGrid : Grid, cell : Cell, weapon : Weapon) : Boolean
        + setPosition(cell : Cell)
    }
    class Tornado extends Trap {
        +<<create>>Tornado(cell : Cell)
        + Tornado()
        + getTrapType() : TrapTypes
        + execTrap(attackGrid : Grid, receiveGrid : Grid, cell : Cell, weapon : Weapon) : Boolean
    }
    class BlackHole extends Trap {
        +<<create>>BlackHole(cell : Cell)
        + BlackHole()
        + getTrapType() : TrapTypes
        + execTrap(attackGrid : Grid, receiveGrid : Grid, cell : Cell, weapon : Weapon) : Boolean
    }
    enum TrapTypes <<enum>>{
        BLACKHOLE
        TORNADO
        + toString() : String
    }
    }

    package weapons #dfdf40 {
        abstract Weapon <<abstract>> implements model.Placeable {
            + getSize() : Integer
            + getCell(index: int) : Cell
            + hasThisPosition(cell: Cell) : Boolean
            + getType() : PlaceableTypes
            {abstract} getWeaponType() : WeaponTypes
            {abstract} execShoot(grid: Grid, cell: Cell) : boolean
        }
        class Missile extends Weapon {
            + execShoot(grid : Grid, cell : Cell) : Boolean
            + getWeaponType() : WeaponTypes
        }
        class IslandSearch extends Weapon {
            - _player : Player
            +<<create>>IslandSearch(player : Player)
            + execShoot(grid : Grid, cell : Cell) : Boolean
            + getWeaponType() : WeaponTypes
        }
        class Bomb extends Weapon {
            + execShoot(grid : Grid, cell : Cell) : Boolean
            - applyImpact(grid : Grid, cell : Cell) : Integer
            + getWeaponType() : WeaponTypes
        }
        class Sonar extends Weapon {
            + execShoot(grid : Grid, cell : Cell) : Boolean
            + getWeaponType() : WeaponTypes
        }
        enum WeaponTypes <<enum>>{
            MISSILE
            ISLANDSEARCH
            BOMB
            SONAR
            + toString() : String
        }
    }

    class Cell {
        - _x : Integer
        - _y : Integer
        + <<create>>Cell(x : Integer, y : Integer)
        + Cell(cell : Cell)
        + getX() : Integer
        + getY() : Integer
        + setX(x : Integer)
        + setY(y : Integer)
        + equals(cell : Cell) : Boolean
    }

}

package controller #6999ff {
    package bots #88bbff {
    interface Bot <<interface>>{
        + placeShips(player : Integer, model : Game, controller : GameController, numberPerShip: Map<ShipTypes, Integer>)
        + shoot(player : Integer, model : Game, controller : GameController)
    }

    class RandomBot implements Bot{
        - _random : Random
        + <<create>>RandomBot()
        + placeShips(player: int, model: Game, controller: GameController, numberPerShip: Map<ShipTypes, Integer>)
        + shoot(player: int, model: Game, controller: GameController)
    }

    class SmartBot implements Bot, model.GridObserver {
        - _random : Random
        - _gridSize : Integer
        - _hunting : Boolean
        +<<create>>SmartBot()
        + placeShips(player: int, model: Game, controller: GameController, numberPerShip: Map<ShipTypes, Integer>)
        + shoot(player: int, model: Game, controller: GameController)
        + updateShoot(player : Integer, posx : Integer, posy : Integer, hit : Boolean)
        - addAdjacentTargets(x : Integer, y : Integer)
        - addIfValid(x : Integer, y : Integer)
        - randomCell() : Cell
        + updateTrapActivated(player : Integer, pox : Integer, posy : Integer, trapType : TrapTypes)
        + updateSearch(player : Integer, posx : Integer, posy : Integer, objectFound : WeaponTypes)
        + updateShipCellPlaced(player : Integer, posx : Integer, posy : Integer)
        + updateTrapPlaced(player : Integer, posx : Integer, posy : Integer, trapType : TrapTypes)
        + updateWeaponPlacedOnIsland(player : Integer, posx : Integer, posy : Integer, weaponType : WeaponTypes)
        + updateShipCellDrowned(player : Integer, posx : Integer, posy : Integer)
        + updateNoMoreShips(player : Integer)
    }


    }
    class GameController {
        - _model : Game
        - _bot : Bot
        + <<create>>GameController(model : Game, bot : Bot)
        + setPlayerName(name : String)
        + setGrid(size : Integer, islandMode : Boolean)
        + setNumberPerShip(numberPerShip : Map<ShipTypes, Integer>) : Boolean
        + botPlaceObjects(player: Integer)
        + placeTrapOnGrid(player : Integer, indexTrap : Integer, posx : Integer, posy : Integer) : Boolean
        + placeShipOnGrid(player : Integer, type : ShipTypes, posx : Integer, posy : Integer, axis : Axis) : Boolean
        + placeWeaponOnIsland(player : Integer, weaponIndex : Integer, posx : Integer, posy : Integer) : Boolean
        + setWeapon(player : Integer, weaponIndex : Integer) : Boolean
        + shootOnGrid(player : Integer, posx : Integer, posy : Integer) : Boolean
        + washGrid(player : Integer)
    }

    class NavigationController {
        - _layout : CardLayout
        - _container : JPanel
        - _views : Map<String, JPanel>
        +<<create>>NavigationController(layout : CardLayout, container : JPanel)
        + saveCard(name : String, view : JPanel)
        + show(name : String)
        + showConfig()
        + showPlacement()
        + showGame(gridPanel : GridPanel)
        + showEnd()
    }
}

package view #99ff99 {
    package themes #11eedd {
        interface Theme <<interface>> {
            + normalFont() : Font
            + boldFont() : Font
            + titleFont() : Font
            + button(button : AbstractButton)
            + buttonConfigMinusTheme(button : AbstractButton)
            + buttonConfigPlusTheme(button : AbstractButton)
        }
        class GlobalTheme implements Theme {
            - _normalFont : Font
            - _boldFont : Font
            - _titleFont
            +<<create>>GlobalTheme()
            + normalFont() : Font
            + boldFont() : Font
            + titleFont() : Font
            + button(button : AbstractButton)
            + buttonConfigMinusTheme(button : AbstractButton)
            + buttonConfigPlusTheme(button : AbstractButton)
        }
    }
    package components #44bb44 {
        class TitleBanner <<extends JPanel>> {
            - _title
            +<<create>>TitleBanner()
            +<<create>>TitleBanner(text : String)
            + setText(text : String)
        }
        class GridPanel <<extends JPanel>> implements model.GridObserver {
            - _model : Game
            - _controller : GameController
            - _mode : GridMode
            - _grid : JButton[][]
            - _axis : Axis
            - _shipType : ShipTypes
            - _trapIndex : Integer
            - _weaponIndex : Integer
            +<<create>>GridPanel(model : Game, controller : GameController, mode : GridMode)
            + setMode(mode : GridMode)
            - draw()
            + resetView()
            + setTypePlacement(shipType : ShipTypes, trapIndex : Integer, weaponIndex : Integer)
            + setAxisPlacement(axis : Axis)
            - buttonClicked(button : JButton)
            + updateShoot(player : Integer, posx : Integer, posy : Integer, hit : Boolean)
            + updateTrapActivated(player : Integer, pox : Integer, posy : Integer, trapType : TrapTypes)
            + updateSearch(player : Integer, posx : Integer, posy : Integer, objectFound : WeaponTypes)
            + updateShipCellPlaced(player : Integer, posx : Integer, posy : Integer)
            + updateTrapPlaced(player : Integer, posx : Integer, posy : Integer, trapType : TrapTypes)
            + updateWeaponPlacedOnIsland(player : Integer, posx : Integer, posy : Integer, weaponType : WeaponTypes)
            + updateShipCellDrowned(player : Integer, posx : Integer, posy : Integer)
            + updateNoMoreShips(player : Integer)
        }
        enum GridMode {
            PLACEMENT
            ATTACK
            RECEIVE
        }
        class InfosPanel <<extends JPanel>>{
            +<<create>>InfosPanel(theme: Theme, shootNumber: int, shootInWater: int, shipsDrowned: int, weaponsUsed: List<WeaponTypes>, trapsActivated: List<TrapTypes>, weaponsFound: List<WeaponTypes>, weaponsNotFound: List<WeaponTypes>)
        }
    }

    class GraphicalView <<extends JFrame>>{
        - _controller : GameController
        - _model : Game
        - _navigationController : NavigationController
        - _theme : Theme
        - _cardLayout : CardLayout
        - _mainPanel : JPanel
        +<<create>>GraphicalView(controller : GameController, model : Game)
    }

    class ConfigScreen <<extends JPanel>> {
        - _controller : GameController
        - _model : Game
        - _navigationController : NavigationController
        - _theme : Theme
        - _leftPanel : JPanel
        - _rightPanel : JPanel
        - _pseudoField : JTextField
        - _sizeGroup : ButtonGroup
        - _islandGroup : ButtonGroup
        - _maxShipsCells : Integer
        - _labelMaxCellsShip : JLabel
        - _labelUsedCells : JLabel
        - _labelNumAircraftCarrier : JLabel
        - _labelNumCruiser : JLabel
        - _labelNumDestroyer : JLabel
        - _labelNumSubmarine : JLabel
        - _labelNumTorpedo : JLabel
        - _plusAircraftCarrier : JButton
        - _plusCruiser : JButton
        - _plusDestroyer : JButton
        - _plusSubmarine : JButton
        - _plusTorpedo : JButton
        - _btnAccepter : JButton
        - _btnSuivant : JButton
        +<<create>>ConfigScreen(controller : GameController, model : Game, navigationController : NavigationController, theme : Theme)
        - draw()
        - setEnabledPanel(panel : JComponent, enabled : Boolean)
        - accept()
        - next()
        - decrementNumberOfShip(number : Integer) : Integer
        - incrementNumberOfShip(number : Integer) : Integer
        - updateUsedCelles()
    }
     class PlacementScreen <<extends JPanel>>{
        - _controller : GameController
        - _model : Game
        - _navigationController : NavigationController
        - _theme : Theme
        - _gridPanel : GridPanel
        +<<create>>PlacementScreen(controller : GameController, model : Game, navigationController : NavigationController, theme : Theme)
        + onShow()
        - randomGeneration()
        - validation()
     }
    class GameScreen <<extends JPanel>>{
        - _controller : GameController
        - _model : Game
        - _navigationController : NavigationController
        - _theme : Theme
        - _gridPanelAttack : GridPanel
        - _gridPanelReceive : GridPanel
        - _title : TitleBanner
        - _panelArmes : JPanel
        +<<create>>GameScreen(controller : GameController, model : Game, navigationController : NavigationController, theme : Theme)
        + onShow()
        + setPlayerShipsGrid(gridPanel : GridPanel)
        - createInfoLabel(text : String) : JLabel
        - addWeapon(indexWeapon : Integer, weaponType : WeaponTypes)
        - selectWeapon(selectedButton : JButton)
        + updateNoMoreShips(player : Integer)
        + updateTurnNum(turnNum : Integer)
        + updateWeaponFound(player : Integer, weaponType : WeaponTypes)
    }
    class EndScreen <<extends JPanel>>{
        - _controller : GameController
        - _model : Game
        - _navigationController : NavigationController
        - _theme : Theme
        +<<create>>EndScreen(controller : GameController, model : Game, navigationController : NavigationController, theme : Theme)
        + onShow()
    }
}

class Main {
}

Weapon ..> PlaceableTypes : "<<uses>>"
Trap ..> PlaceableTypes : "<<uses>>"
Impact ..> PlaceableTypes : "<<uses>>"
Ship ..> PlaceableTypes : "<<uses>>"
IslandPart ..> PlaceableTypes : "<<uses>>"

ShipFactory ..> Ship : "<<create>>"
Ship o--> "1\n- _type" ShipTypes : "> is this type of ship"

Ship o--> "*\n- _positions" Cell : "> has for coordinates"
Impact o--> "1\n- _position" Cell : "> has for coordinates"
Trap o--> "1\n# _position" Cell : "> has for coordinates"
IslandPart o--> "1\n- _position" Cell : "> has for coordinates"

IslandPart o--> "1\n- _placedObject" Placeable : "> stock a placeable"


Grid o--> "*\n- _placedObjects" Placeable : "> contains"
Grid o--> "*\n_observers" GridObserver : > notify
Player o--> "1\n- _grid" Grid : "> has for grid"
Player o--> "*\n- _weaponInventory" Weapon : "> can use theses weapons"
Player o--> "1\n- _equippedWeapon" Weapon : "> has this strategy of attack"
Game *--> "2\n- _players" Player : "> has 2 players"
Game *--> "*\n' _traps" Trap : "> knows which traps can be placed"

SmartBot o--> "*\n- _shotsDone" Cell : "> keeps shot already done"
SmartBot o--> "*\n- _targets" Cell : "> keeps cells to shoot later in a stack"

GameController o--> "1\n- _model" Game : "> Manipulate"
GraphicalView o--> "1\n- _model" Game : "> Consult"
GraphicalView o--> "1\n- _controller" GameController : "> Transmit user's demands"
GraphicalView *--> "1\n- _controller" NavigationController : "> view is selected by"
GraphicalView *--> "1\n- _theme" Theme : "> apply this theme"

GraphicalView ..> ConfigScreen : "<< create >>"
GraphicalView ..> PlacementScreen : "<< create >>"
GraphicalView ..> GameScreen : "<< create >>"
GraphicalView ..> EndScreen : "<< create >>"

ConfigScreen *--> "1\n- _titleBanner" TitleBanner : "<< create >>"
GameScreen *--> "1\n- _titleBanner" TitleBanner : "<< create >>"
EndScreen *--> "1\n- _titleBanner" TitleBanner : "<< create >>"

PlacementScreen *--> "1\n- _grid" GridPanel : "> display 1 grid"

GameScreen *--> "2\n- _grids" GridPanel : "> display 2 grids"
GameScreen *--> "1\n- _infos" InfosPanel : "> display infos"


Main ..> Game : "<<uses>>"
Main ..> GameController : "<<uses>>"
Main ..> GraphicalView : "<<uses>>"




@enduml
