@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam linetype ortho
hide enum methods


package model #eeaaff{

    class Game {
        - _turnNum : Integer
        - _gridSize : Integer
        - _joueur : Integer
        - _islandMode : Boolean
        - _numberPerShip : Integer[*]
        +<<create>>Game()
        + getTurnNum() : Integer
        + getTrapInventorySize() : Integer
        + getTrapInIventory(indexTrap : Integer) : Trap
        + setPlayerName(name : String)
        + setGrid(width : Integer, height : Integer, islandMode : Boolean)
        + getGridSize() : Integer
        + otherPlayer(joueur : Integer) : Integer
        + getMaxShipsPossible() : Integer
        + setMaxShipsCells(maxShips : Integer) : Boolean
        + setNumberPerShip(numberPerShip : Integer[*]) : Boolean
        + placeTrapOnGrid(joueur : Integer, trap : Trap) : Boolean
        + placeShipOnGrid(joueur : Integer, ship : Ship) : Boolean
        + placeWeaponOnIsland(joueur : Integer, weapon : Weapon, cell : Cell) : Boolean
        + shootOnGrid(joueur : Integer, cell : Cell) : Boolean
        + setWeapon(joueur : Integer, weaponIndex : Integer) : Boolean
        + isTheGameFinished() : Boolean
        + whoWon() : Player
    }

    enum Axis <<enum>>{
        VERTICAL
        HORIZONTAL
    }

    class Player {
        - _name : String
        +<<create>>Player(name : String, grid : Grid)
        + getName() : String
        + getGrid() : Grid
        + setGrid(grid : Grid)
        + addGridObserver(observer : GridObserver)
        + setMaxShipsCells(maxShipsCells : Integer)
        + getObjectByPosition(cell : Cell) : Placeable
        + placeTrap(trap : Trap) : Boolean
        + placeShip(ship : Ship) : Boolean
        + placeWeaponOnIsland(joueur : Integer, weapon : Weapon, cell : Cell) : Boolean
        + shoot(otherPlayer : Player, cell : Cell) : Boolean
        + addWeaponInInventory(weapon : Weapon)
        + getEquippedWeapon() : Weapon
        + getWeaponInventorySize() : Integer
        + getWeaponInInventory(weaponIndex : Integer) : Weapon
        + hasNoMoreShips() : Boolean
    }

    class Grid {
        - _width : Integer
        - _height : Integer
        - _islandMode : Boolean
        - _maxShipsCells : Integer
        +<<create>>Grid(width : Integer, height : Integer)
        +<<create>>Grid(width : Integer, height : Integer, islandMode : Boolean)
        - constructIsland()
        + addObserver(observer : GridObserver)
        + notifyObserversShoot(posx : Integer, posy : Integer, hit : Boolean)
        + notifyObserversTrapActivated(posx : Integer, posy : Integer)
        + notifyObserversSearch(posx : Integer, posy : Integer, objectFound : PlaceableTypes)
        + notifyObserversShipCellDrowned(posx : Integer, posy : Integer)
        + setMaxShipsCells(maxShipsCells : Integer)
        + isOccupied(cell : Cell) : Boolean
        + isOccupiedBy(cell : Cell, PlaceableTypes type) : Boolean
        + getObjectByPosition(cell : Cell) : Placeable
        + isInGrid(cell : Cell) : Boolean
        + canPlaceObject(placeable : Placeable) : Boolean
        + placeObject(placeable : Placeable) : Boolean
        + placeImpact(cell : Cell) : Boolean
        + shoot(cell : Cell, weapon : Weapon) : Boolean
        + isTheShipDrowned(ship : Ship) : Boolean
        + getIslandObject(cell : Cell) : Placeable
        + placeWeaponOnIsland(weapon : Weapon, cell : Cell) : Boolean
        + allShipsDead() : Boolean
    }
    interface GridObserver <<interface>> {
        + updateShoot(joueur : Integer, posx : Integer, posy : Integer, hit : Boolean)
        + updateTrapActivated(joueur : Integer, pox : Integer, posy : Integer)
        + updateSearch(joueur : Integer, posx : Integer, posy : Integer, objectFound : PlaceableTypes)
        + updateShipCellPlaced(joueur : Integer, posx : Integer, posy : Integer)
        + updateTrapPlaced(joueur : Integer, posx : Integer, posy : Integer, trapType : TrapTypes)
        + updateShipCellDrowned(joueur : Integer, posx : Integer, posy : Integer)
    }

    enum PlaceableTypes <<enum>>{
        SHIP
        TRAP
        IMPACT
        ISLANDPART
        WEAPON
    }
    interface Placeable <<interface>> {
        + getSize() : Integer
        + getCell(index : Integer) : Cell
        + hasThisPosition(cell : Cell) : Boolean
        + getType() : PlaceableTypes
    }
    class PlaceableFactory {
        +<<create>>PlaceableFactory()
        + createShip(positions : Cell[])
        + createImpact(cell : Cell)
        + createIslandPart(cell : Cell)
        + createWeaponBomb()
        + createWeaponMissile()
        + createWeaponSonar()
        + createTrapTornado(cell : Cell)
        + createTrapBlackHole(cell : Cell)
    }

    class Impact implements Placeable {
        +<<create>>Impact(cell : Cell)
        + getSize() : Integer
        + getCell(index : Integer) : Cell
        + hasThisPosition(cell : Cell) : Boolean
    }

    class IslandPart implements Placeable{
        + <<create>>Island(cell : Cell)
        + getSize() : Integer
        + getCell(index : Integer) : Cell
        + hasThisPosition(cell : Cell) : Boolean
        + isThereAnObject() : Boolean
        + getPlacedObject() : Placeable
        + setPlacedObject(placeable : Placeable)
    }

    class Ship implements Placeable {
        + <<create>>Ship(positions : Cell[])
        + getSize() : Integer
        + getCell(index : Integer) : Cell
        + hasThisPosition(cell : Cell) : Boolean
    }
    class ShipFactory {
        + createAircraftCarrier() : Ship
        + createCruiser() : Ship
        + createDestroyer() : Ship
        + createSubmarine() : Ship
        + createTorpedo() : Ship
    }
    enum ShipTypes <<enum>>{
        AircraftCarrier
        Cruiser
        Destroyer
        Submarine
        Torpedo
        + getSize() : Integer
    }

    package traps #ff4040 {
    abstract Trap <<abstract>> implements model.Placeable {
        +<<create>>Trap(cell : Cell)
        + getSize() : Integer
        + getCell(index : Integer) : Cell
        + hasThisPosition(cell : Cell) : Boolean
        + setPosition(cell : Cell)
    }
    class Tornado extends Trap {
        +<<create>>Tornado(cell : Cell)
    }
    class BlackHole extends Trap {
        +<<create>>BlackHole(cell : Cell)
    }
    }

    package weapons #dfdf40 {
        abstract Weapon <<abstract>> implements model.Placeable {
            + <<create>>Weapon()
            + getSize() : Integer
            + getCell(index : Integer) : Cell
            + hasThisPosition(cell : Cell) : Boolean
            + setPosition(cell : Cell)
            + execShoot(grid : Grid, cell : Cell) : Boolean

        }
        class Missile extends Weapon {
            +<<create>>Missile()
            + execShoot(grid : Grid, cell : Cell) : Boolean
        }
        class IslandSearch extends Weapon {
            - _player : Player
            +<<create>>IslandSearch(player : Player)
            + execShoot(grid : Grid, cell : Cell) : Boolean
        }
        class Bomb extends Weapon {
            +<<create>>Bomb()
            + execShoot(grid : Grid, cell : Cell) : Boolean
            - applyImpact(grid : Grid, cell : Cell) : Integer
        }
        class Sonar extends Weapon {
            +<<create>>Sonar()
            + execShoot(grid : Grid, cell : Cell) : Boolean
        }
    }

    class Cell {
        - _x : Integer
        - _y : Integer
        + <<create>>Cell(x : Integer, y : Integer)
        + getX() : Integer
        + getY() : Integer
        + setX(x : Integer)
        + setY(y : Integer)
    }

}

package controller #6999ff {
    class GameController {
        + <<create>>GameController(model : Game)
        + setPlayerName(name : String)
        + setGrid(size : Integer, islandMode : Boolean)
        + setMaxShipsCells(maxShips : Integer) : Boolean
        + setNumberPerShip(numberPerShip : Integer[*]) : Boolean
        + placeTrapOnGrid(joueur ; Integer, indexTrap : Integer, posx : Integer, posy : Integer) : Boolean
        + placeShipOnGrid(joueur : Integer, type : ShipTypes, posx : Integer, posy : Integer, axis : Axis) : Boolean
        + setWeapon(joueur : Integer, weaponIndex : Integer) : Boolean
        + shootOnGrid(joueur : Integer, posx : Integer, posy : Integer) : Boolean
    }

    class NavigationController {
        - _layout : CardLayout
        - _container : JPanel
        +<<create>>NavigationController(layout : CardLayout, container : JPanel)
        + showConfig()
        + showPlacement()
        + showGame()
        + showEnd()
    }
}

package view #99ff99 {
    package themes #11eedd {
        interface Theme <<interface>> {
            + normalFont() : Font
            + boldFont() : Font
            + titleFont() : Font
            + button(text : String) : JButton
        }
        class GlobalTheme implements Theme {
            - _normalFont : Font
            - _boldFont : Font
            - _titleFont
            +<<create>>GlobalTheme()
            + normalFont() : Font
            + boldFont() : Font
            + titleFont() : Font
            + button(text : String) : JButton
        }
    }
    package components #44bb44 {
        class TitleBanner <<extends JPanel>> {
            +<<create>>TitleBanner()
        }
        class GridPanel <<extends JPanel>> implements model.GridObserver {
            - _grid : JButton[][]
            +<<create>>GridPanel(gridSize : Integer)
        }
        enum GridMode {
            PLACEMENT
            ATTACK
            RECEIVE
        }
        class InfosPanel <<extends JPanel>>{
            +<<create>>InfosPanel()
        }
    }

    class GraphicalView <<extends JFrame>>{
        - _layout : CardLayout
        - _mainPanel : JPanel
        +<<create>>GraphicalView(model : Game, controller : GameController)
    }

    class ConfigScreen <<extends JPanel>> {
        +<<create>>ConfigScreen(controller : GameScreen, model : Game, navigationController : NavigationController, theme : Theme)
        + validation()
    }
     class PlacementScreen <<extends JPanel>>{
        +<<create>>PlacementScreen(controller : GameScreen, model : Game, navigationController : NavigationController, theme : Theme)
        + validation()
     }
    class GameScreen <<extends JPanel>>{
        +<<create>>GameScreen(controller : GameScreen, model : Game, navigationController : NavigationController, theme : Theme)
    }
    class EndScreen <<extends JPanel>>{
        +<<create>>EndScreen(controller : GameScreen, model : Game, navigationController : NavigationController, theme : Theme)
    }


}


class Main {
}

Weapon ..> PlaceableTypes : "<<uses>>"
Trap ..> PlaceableTypes : "<<uses>>"
Impact ..> PlaceableTypes : "<<uses>>"
Ship ..> PlaceableTypes : "<<uses>>"
IslandPart ..> PlaceableTypes : "<<uses>>"

PlaceableFactory ..> Placeable : "<<uses>>"
PlaceableFactory ..> Impact : "<<create>>"
PlaceableFactory ..> IslandPart : "<<create>>"
PlaceableFactory ..> Ship : "<<create>>"
PlaceableFactory ..> Bomb : "<<create>>"
PlaceableFactory ..> Missile : "<<create>>"
PlaceableFactory ..> Sonar : "<<create>>"
PlaceableFactory ..> Tornado : "<<create>>"
PlaceableFactory ..> BlackHole : "<<create>>"

ShipFactory ..> Ship : "<<create>>"
Ship o--> "1\n- _type" ShipTypes : "> is this type of ship"

Ship o--> "*\n- _positions" Cell : "> has for coordinates"
Impact o--> "1\n- _position" Cell : "> has for coordinates"
Trap o--> "1\n# _position" Cell : "> has for coordinates"
IslandPart o--> "1\n- _position" Cell : "> has for coordinates"

IslandPart o--> "1\n- _placedObject" Placeable : "> stock a placeable"


Grid o--> "*\n- _placedObjects" Placeable : "> contains"
Grid o--> "*\n_observers" GridObserver : > notify
Player o--> "1\n- _grid" Grid : "> has for grid"
Player o--> "*\n- _weaponInventory" Weapon : "> can use theses weapons"
Player o--> "1\n- _equippedWeapon" Weapon : "> has this strategy of attack"
Game *--> "2\n- _players" Player : "> has 2 players"
Game *--> "*\n' _traps" Trap : "> knows which traps can be placed"

GameController o--> "1\n- _model" Game : "> Manipulate"
GraphicalView o--> "1\n- _model" Game : "> Consult"
GraphicalView o--> "1\n- _controller" GameController : "> Transmit user's demands"
GraphicalView *--> "1\n- _controller" NavigationController : "> view is selected by"
GraphicalView *--> "1\n- _theme" Theme : "> apply this theme"

GraphicalView ..> ConfigScreen : "<< create >>"
GraphicalView ..> PlacementScreen : "<< create >>"
GraphicalView ..> GameScreen : "<< create >>"
GraphicalView ..> EndScreen : "<< create >>"

ConfigScreen *--> "1\n- _titleBanner" TitleBanner : "<< create >>"
GameScreen *--> "1\n- _titleBanner" TitleBanner : "<< create >>"
EndScreen *--> "1\n- _titleBanner" TitleBanner : "<< create >>"

PlacementScreen *--> "1\n- _grid" GridPanel : "> display 1 grid"

GameScreen *--> "2\n- _grids" GridPanel : "> display 2 grids"
GameScreen *--> "1\n- _infos" InfosPanel : "> display infos"


Main ..> Game : "<<uses>>"
Main ..> GameController : "<<uses>>"
Main ..> GraphicalView : "<<uses>>"




@enduml
